"""add cfop_reference table with ADE COTEPE data

Revision ID: 003
Revises: 002
Create Date: 2026-05-26

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "003"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# fmt: off
# CFOPs per ADE COTEPE/ICMS 42/2009 and subsequent updates (ADE COTEPE 65/2018)
# Fields: (cfop, descricao, tipo_operacao, escopo, permite_devolucao)
_CFOPS = [
    # ── Entradas internas (1xxx) ────────────────────────────────────────────
    ("1101", "Compra para industrialização ou produção rural", "entrada", "intraestadual", False),
    ("1102", "Compra para comercialização", "entrada", "intraestadual", False),
    ("1111", "Compra para industrialização de mercadoria recebida anteriormente em consignação industrial", "entrada", "intraestadual", False),
    ("1113", "Compra para industrialização, de mercadoria produzida pelo encomendante", "entrada", "intraestadual", False),
    ("1116", "Compra para industrialização originada de encomenda para recebimento futuro", "entrada", "intraestadual", False),
    ("1117", "Compra de mercadoria para uso ou consumo", "entrada", "intraestadual", False),
    ("1118", "Compra de mercadoria para industrialização e produção rural sob o regime de drawback", "entrada", "intraestadual", False),
    ("1120", "Compra para industrialização, em venda à ordem, já recebida do vendedor remetente", "entrada", "intraestadual", False),
    ("1121", "Compra para comercialização, em venda à ordem, já recebida do vendedor remetente", "entrada", "intraestadual", False),
    ("1122", "Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente", "entrada", "intraestadual", False),
    ("1124", "Industrialização efetuada por outra empresa", "entrada", "intraestadual", False),
    ("1125", "Industrialização efetuada por outra empresa quando a mercadoria remetida para esse fim não transitou pelo estabelecimento adquirente da mercadoria", "entrada", "intraestadual", False),
    ("1126", "Compra para utilização na prestação de serviço sujeita ao ISSQN", "entrada", "intraestadual", False),
    ("1128", "Compra para utilização na prestação de serviço sujeita ao ISSQN", "entrada", "intraestadual", False),
    ("1150", "Transferência para industrialização ou produção rural", "entrada", "intraestadual", False),
    ("1151", "Transferência para comercialização", "entrada", "intraestadual", False),
    ("1152", "Transferência de energia elétrica para distribuição", "entrada", "intraestadual", False),
    ("1153", "Transferência para utilização na prestação de serviço", "entrada", "intraestadual", False),
    ("1200", "Devoluções de vendas de produção do estabelecimento", "entrada", "intraestadual", True),
    ("1201", "Devolução de venda de produção do estabelecimento", "entrada", "intraestadual", True),
    ("1202", "Devolução de venda de mercadoria adquirida ou recebida de terceiros", "entrada", "intraestadual", True),
    ("1203", "Devolução de venda de produção do estabelecimento, destinada à ZFM ou ALC", "entrada", "intraestadual", True),
    ("1204", "Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à ZFM ou ALC", "entrada", "intraestadual", True),
    ("1205", "Anulação de valor relativo a prestação de serviço de comunicação", "entrada", "intraestadual", False),
    ("1206", "Anulação de valor relativo a prestação de serviço de transporte", "entrada", "intraestadual", False),
    ("1207", "Anulação de valor relativo à venda de energia elétrica", "entrada", "intraestadual", False),
    ("1208", "Devolução de produção do estabelecimento, remetida em transferência", "entrada", "intraestadual", True),
    ("1209", "Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência", "entrada", "intraestadual", True),
    ("1210", "Devolução de compras para utilização na prestação de serviço", "entrada", "intraestadual", True),
    ("1250", "Compras de energia elétrica", "entrada", "intraestadual", False),
    ("1251", "Compra de energia elétrica para distribuição ou comercialização", "entrada", "intraestadual", False),
    ("1252", "Compra de energia elétrica por estabelecimento industrial", "entrada", "intraestadual", False),
    ("1253", "Compra de energia elétrica por estabelecimento comercial", "entrada", "intraestadual", False),
    ("1254", "Compra de energia elétrica por estabelecimento prestador de serviço de transporte", "entrada", "intraestadual", False),
    ("1255", "Compra de energia elétrica por estabelecimento prestador de serviços comunicação", "entrada", "intraestadual", False),
    ("1256", "Compra de energia elétrica por estabelecimento de produtor rural", "entrada", "intraestadual", False),
    ("1257", "Compra de energia elétrica para uso ou consumo", "entrada", "intraestadual", False),
    ("1300", "Aquisições de serviços de comunicação", "entrada", "intraestadual", False),
    ("1301", "Aquisição de serviço de comunicação para execução de serviço da mesma natureza", "entrada", "intraestadual", False),
    ("1302", "Aquisição de serviço de comunicação por estabelecimento industrial", "entrada", "intraestadual", False),
    ("1303", "Aquisição de serviço de comunicação por estabelecimento comercial", "entrada", "intraestadual", False),
    ("1304", "Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte", "entrada", "intraestadual", False),
    ("1305", "Aquisição de serviço de comunicação por estabelecimento prestador de serviço de comunicação", "entrada", "intraestadual", False),
    ("1306", "Aquisição de serviço de comunicação por estabelecimento de produtor rural", "entrada", "intraestadual", False),
    ("1307", "Aquisição de serviço de comunicação para uso ou consumo", "entrada", "intraestadual", False),
    ("1350", "Aquisições de serviços de transporte", "entrada", "intraestadual", False),
    ("1351", "Aquisição de serviço de transporte para execução de serviço da mesma natureza", "entrada", "intraestadual", False),
    ("1352", "Aquisição de serviço de transporte por estabelecimento industrial", "entrada", "intraestadual", False),
    ("1353", "Aquisição de serviço de transporte por estabelecimento comercial", "entrada", "intraestadual", False),
    ("1354", "Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação", "entrada", "intraestadual", False),
    ("1355", "Aquisição de serviço de transporte por estabelecimento de produtor rural", "entrada", "intraestadual", False),
    ("1356", "Aquisição de serviço de transporte por estabelecimento de prestador de serviço de transporte", "entrada", "intraestadual", False),
    ("1360", "Aquisição de serviço de transporte por estabelecimento de contribuinte não obrigado ao pagamento do ICMS", "entrada", "intraestadual", False),
    ("1400", "Entradas de mercadorias sujeitas ao regime de substituição tributária", "entrada", "intraestadual", False),
    ("1401", "Compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária", "entrada", "intraestadual", False),
    ("1403", "Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária", "entrada", "intraestadual", False),
    ("1406", "Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária", "entrada", "intraestadual", False),
    ("1407", "Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária", "entrada", "intraestadual", False),
    ("1408", "Transferência para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária", "entrada", "intraestadual", False),
    ("1409", "Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária", "entrada", "intraestadual", False),
    ("1410", "Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária", "entrada", "intraestadual", True),
    ("1411", "Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária", "entrada", "intraestadual", True),
    ("1414", "Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento", "entrada", "intraestadual", False),
    ("1415", "Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento", "entrada", "intraestadual", False),
    ("1450", "Sistemas de integração e parceria rural", "entrada", "intraestadual", False),
    ("1451", "Retorno de animal do campo para o estabelecimento", "entrada", "intraestadual", False),
    ("1452", "Retorno de insumo não utilizado na produção", "entrada", "intraestadual", False),
    ("1500", "Entradas de mercadorias remetidas com fim específico de exportação e eventuais devoluções", "entrada", "intraestadual", False),
    ("1501", "Entrada de mercadoria recebida com fim específico de exportação", "entrada", "intraestadual", False),
    ("1503", "Entrada decorrente de devolução de produto remetido com fim específico de exportação", "entrada", "intraestadual", True),
    ("1504", "Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação", "entrada", "intraestadual", True),
    ("1505", "Entrada decorrente de devolução de mercadorias remetidas para formação de lote de exportação", "entrada", "intraestadual", True),
    ("1550", "Operações com bens de ativo imobilizado e materiais de uso e consumo", "entrada", "intraestadual", False),
    ("1551", "Compra de bem para o ativo imobilizado", "entrada", "intraestadual", False),
    ("1552", "Transferência de bem do ativo imobilizado", "entrada", "intraestadual", False),
    ("1553", "Devolução de transferência de bem do ativo imobilizado", "entrada", "intraestadual", True),
    ("1554", "Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento", "entrada", "intraestadual", False),
    ("1555", "Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento", "entrada", "intraestadual", False),
    ("1556", "Compra de material para uso ou consumo", "entrada", "intraestadual", False),
    ("1557", "Transferência de material de uso ou consumo", "entrada", "intraestadual", False),
    ("1600", "Créditos e ressarcimentos de ICMS", "entrada", "intraestadual", False),
    ("1601", "Recebimento, por transferência, de crédito de ICMS", "entrada", "intraestadual", False),
    ("1602", "Recebimento, por transferência, de saldo credor de ICMS de outro estabelecimento da mesma empresa", "entrada", "intraestadual", False),
    ("1603", "Ressarcimento de ICMS retido por substituição tributária", "entrada", "intraestadual", False),
    ("1604", "Lançamento do crédito relativo à compra de bem para o ativo imobilizado", "entrada", "intraestadual", False),
    ("1605", "Recebimento, por transferência, de saldo devedor de ICMS de outro estabelecimento da mesma empresa", "entrada", "intraestadual", False),
    ("1650", "Entradas de combustíveis, lubrificantes, aditivos e agentes de limpeza", "entrada", "intraestadual", False),
    ("1651", "Compra de combustível ou lubrificante para industrialização subseqüente", "entrada", "intraestadual", False),
    ("1652", "Compra de combustível ou lubrificante para comercialização", "entrada", "intraestadual", False),
    ("1653", "Compra de combustível ou lubrificante por consumidor ou usuário final", "entrada", "intraestadual", False),
    ("1658", "Transferência de combustível ou lubrificante para industrialização subseqüente", "entrada", "intraestadual", False),
    ("1659", "Transferência de combustível ou lubrificante para comercialização", "entrada", "intraestadual", False),
    ("1660", "Devolução de venda de combustível ou lubrificante destinados à industrialização subseqüente", "entrada", "intraestadual", True),
    ("1661", "Devolução de venda de combustível ou lubrificante destinados à comercialização", "entrada", "intraestadual", True),
    ("1662", "Devolução de venda de combustível ou lubrificante destinados a consumidor ou usuário final", "entrada", "intraestadual", True),
    ("1900", "Outras entradas de mercadorias ou aquisições de serviços", "entrada", "intraestadual", False),
    ("1901", "Entrada para industrialização por encomenda", "entrada", "intraestadual", False),
    ("1902", "Retorno de mercadoria remetida para industrialização por encomenda", "entrada", "intraestadual", False),
    ("1903", "Entrada de mercadoria remetida para industrialização e não aplicada no referido processo", "entrada", "intraestadual", False),
    ("1904", "Retorno de remessa para venda fora do estabelecimento", "entrada", "intraestadual", False),
    ("1905", "Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral", "entrada", "intraestadual", False),
    ("1906", "Retorno de mercadoria remetida para depósito fechado ou armazém geral", "entrada", "intraestadual", False),
    ("1907", "Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral", "entrada", "intraestadual", False),
    ("1908", "Entrada de bem por conta de contrato de comodato", "entrada", "intraestadual", False),
    ("1909", "Retorno de bem remetido por conta de contrato de comodato", "entrada", "intraestadual", False),
    ("1910", "Entrada de bonificação, doação ou brinde", "entrada", "intraestadual", False),
    ("1911", "Entrada de amostra grátis", "entrada", "intraestadual", False),
    ("1912", "Entrada de mercadoria ou bem recebido para demonstração", "entrada", "intraestadual", False),
    ("1913", "Retorno de mercadoria ou bem remetido para demonstração", "entrada", "intraestadual", False),
    ("1914", "Retorno de mercadoria ou bem remetido para exposição ou feira", "entrada", "intraestadual", False),
    ("1915", "Entrada de mercadoria ou bem recebido para conserto ou reparo", "entrada", "intraestadual", False),
    ("1916", "Retorno de mercadoria ou bem remetido para conserto ou reparo", "entrada", "intraestadual", False),
    ("1917", "Entrada de mercadoria recebida em consignação mercantil ou industrial", "entrada", "intraestadual", False),
    ("1918", "Devolução de mercadoria remetida em consignação mercantil ou industrial", "entrada", "intraestadual", True),
    ("1919", "Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial", "entrada", "intraestadual", True),
    ("1920", "Entrada de vasilhame ou sacaria", "entrada", "intraestadual", False),
    ("1921", "Retorno de vasilhame ou sacaria", "entrada", "intraestadual", False),
    ("1922", "Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro", "entrada", "intraestadual", False),
    ("1923", "Entrada de mercadoria recebida do vendedor remetente, em venda à ordem", "entrada", "intraestadual", False),
    ("1924", "Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente", "entrada", "intraestadual", False),
    ("1925", "Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente", "entrada", "intraestadual", False),
    ("1932", "Aquisição de serviços de transporte iniciado em estado diverso", "entrada", "intraestadual", False),
    ("1933", "Aquisição de serviço tributado pelo ISSQN", "entrada", "intraestadual", False),
    ("1934", "Entrada simbólica de mercadoria recebida para depósito fechado ou armazém geral", "entrada", "intraestadual", False),
    ("1949", "Outra entrada de mercadoria ou prestação de serviço não especificada", "entrada", "intraestadual", False),

    # ── Entradas interestaduais (2xxx) ──────────────────────────────────────
    ("2101", "Compra para industrialização ou produção rural", "entrada", "interestadual", False),
    ("2102", "Compra para comercialização", "entrada", "interestadual", False),
    ("2111", "Compra para industrialização de mercadoria recebida anteriormente em consignação industrial", "entrada", "interestadual", False),
    ("2113", "Compra para industrialização, de mercadoria produzida pelo encomendante", "entrada", "interestadual", False),
    ("2116", "Compra para industrialização originada de encomenda para recebimento futuro", "entrada", "interestadual", False),
    ("2117", "Compra de mercadoria para uso ou consumo", "entrada", "interestadual", False),
    ("2118", "Compra de mercadoria para industrialização e produção rural sob o regime de drawback", "entrada", "interestadual", False),
    ("2120", "Compra para industrialização, em venda à ordem, já recebida do vendedor remetente", "entrada", "interestadual", False),
    ("2121", "Compra para comercialização, em venda à ordem, já recebida do vendedor remetente", "entrada", "interestadual", False),
    ("2122", "Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente", "entrada", "interestadual", False),
    ("2124", "Industrialização efetuada por outra empresa", "entrada", "interestadual", False),
    ("2125", "Industrialização efetuada por outra empresa quando a mercadoria remetida para esse fim não transitou pelo estabelecimento adquirente", "entrada", "interestadual", False),
    ("2126", "Compra para utilização na prestação de serviço sujeita ao ISSQN", "entrada", "interestadual", False),
    ("2150", "Transferência para industrialização ou produção rural", "entrada", "interestadual", False),
    ("2151", "Transferência para comercialização", "entrada", "interestadual", False),
    ("2152", "Transferência de energia elétrica para distribuição", "entrada", "interestadual", False),
    ("2153", "Transferência para utilização na prestação de serviço", "entrada", "interestadual", False),
    ("2200", "Devoluções de vendas de produção do estabelecimento", "entrada", "interestadual", True),
    ("2201", "Devolução de venda de produção do estabelecimento", "entrada", "interestadual", True),
    ("2202", "Devolução de venda de mercadoria adquirida ou recebida de terceiros", "entrada", "interestadual", True),
    ("2203", "Devolução de venda de produção do estabelecimento, destinada à ZFM ou ALC", "entrada", "interestadual", True),
    ("2204", "Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à ZFM ou ALC", "entrada", "interestadual", True),
    ("2205", "Anulação de valor relativo a prestação de serviço de comunicação", "entrada", "interestadual", False),
    ("2206", "Anulação de valor relativo a prestação de serviço de transporte", "entrada", "interestadual", False),
    ("2207", "Anulação de valor relativo à venda de energia elétrica", "entrada", "interestadual", False),
    ("2208", "Devolução de produção do estabelecimento, remetida em transferência", "entrada", "interestadual", True),
    ("2209", "Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência", "entrada", "interestadual", True),
    ("2210", "Devolução de compras para utilização na prestação de serviço", "entrada", "interestadual", True),
    ("2250", "Compras de energia elétrica", "entrada", "interestadual", False),
    ("2251", "Compra de energia elétrica para distribuição ou comercialização", "entrada", "interestadual", False),
    ("2252", "Compra de energia elétrica por estabelecimento industrial", "entrada", "interestadual", False),
    ("2253", "Compra de energia elétrica por estabelecimento comercial", "entrada", "interestadual", False),
    ("2301", "Aquisição de serviço de comunicação para execução de serviço da mesma natureza", "entrada", "interestadual", False),
    ("2302", "Aquisição de serviço de comunicação por estabelecimento industrial", "entrada", "interestadual", False),
    ("2303", "Aquisição de serviço de comunicação por estabelecimento comercial", "entrada", "interestadual", False),
    ("2350", "Aquisições de serviços de transporte", "entrada", "interestadual", False),
    ("2351", "Aquisição de serviço de transporte para execução de serviço da mesma natureza", "entrada", "interestadual", False),
    ("2352", "Aquisição de serviço de transporte por estabelecimento industrial", "entrada", "interestadual", False),
    ("2353", "Aquisição de serviço de transporte por estabelecimento comercial", "entrada", "interestadual", False),
    ("2401", "Compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária", "entrada", "interestadual", False),
    ("2403", "Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária", "entrada", "interestadual", False),
    ("2406", "Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária", "entrada", "interestadual", False),
    ("2407", "Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária", "entrada", "interestadual", False),
    ("2410", "Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária", "entrada", "interestadual", True),
    ("2411", "Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária", "entrada", "interestadual", True),
    ("2501", "Entrada de mercadoria recebida com fim específico de exportação", "entrada", "interestadual", False),
    ("2503", "Entrada decorrente de devolução de produto remetido com fim específico de exportação", "entrada", "interestadual", True),
    ("2504", "Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação", "entrada", "interestadual", True),
    ("2550", "Operações com bens de ativo imobilizado e materiais de uso e consumo", "entrada", "interestadual", False),
    ("2551", "Compra de bem para o ativo imobilizado", "entrada", "interestadual", False),
    ("2552", "Transferência de bem do ativo imobilizado", "entrada", "interestadual", False),
    ("2553", "Devolução de transferência de bem do ativo imobilizado", "entrada", "interestadual", True),
    ("2554", "Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento", "entrada", "interestadual", False),
    ("2555", "Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento", "entrada", "interestadual", False),
    ("2556", "Compra de material para uso ou consumo", "entrada", "interestadual", False),
    ("2557", "Transferência de material de uso ou consumo", "entrada", "interestadual", False),
    ("2603", "Ressarcimento de ICMS retido por substituição tributária", "entrada", "interestadual", False),
    ("2651", "Compra de combustível ou lubrificante para industrialização subseqüente", "entrada", "interestadual", False),
    ("2652", "Compra de combustível ou lubrificante para comercialização", "entrada", "interestadual", False),
    ("2653", "Compra de combustível ou lubrificante por consumidor ou usuário final", "entrada", "interestadual", False),
    ("2660", "Devolução de venda de combustível ou lubrificante destinados à industrialização subseqüente", "entrada", "interestadual", True),
    ("2661", "Devolução de venda de combustível ou lubrificante destinados à comercialização", "entrada", "interestadual", True),
    ("2662", "Devolução de venda de combustível ou lubrificante destinados a consumidor ou usuário final", "entrada", "interestadual", True),
    ("2900", "Outras entradas de mercadorias ou aquisições de serviços", "entrada", "interestadual", False),
    ("2901", "Entrada para industrialização por encomenda", "entrada", "interestadual", False),
    ("2902", "Retorno de mercadoria remetida para industrialização por encomenda", "entrada", "interestadual", False),
    ("2903", "Entrada de mercadoria remetida para industrialização e não aplicada no referido processo", "entrada", "interestadual", False),
    ("2904", "Retorno de remessa para venda fora do estabelecimento", "entrada", "interestadual", False),
    ("2905", "Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral", "entrada", "interestadual", False),
    ("2906", "Retorno de mercadoria remetida para depósito fechado ou armazém geral", "entrada", "interestadual", False),
    ("2907", "Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral", "entrada", "interestadual", False),
    ("2908", "Entrada de bem por conta de contrato de comodato", "entrada", "interestadual", False),
    ("2909", "Retorno de bem remetido por conta de contrato de comodato", "entrada", "interestadual", False),
    ("2910", "Entrada de bonificação, doação ou brinde", "entrada", "interestadual", False),
    ("2911", "Entrada de amostra grátis", "entrada", "interestadual", False),
    ("2912", "Entrada de mercadoria ou bem recebido para demonstração", "entrada", "interestadual", False),
    ("2913", "Retorno de mercadoria ou bem remetido para demonstração", "entrada", "interestadual", False),
    ("2914", "Retorno de mercadoria ou bem remetido para exposição ou feira", "entrada", "interestadual", False),
    ("2915", "Entrada de mercadoria ou bem recebido para conserto ou reparo", "entrada", "interestadual", False),
    ("2916", "Retorno de mercadoria ou bem remetido para conserto ou reparo", "entrada", "interestadual", False),
    ("2917", "Entrada de mercadoria recebida em consignação mercantil ou industrial", "entrada", "interestadual", False),
    ("2918", "Devolução de mercadoria remetida em consignação mercantil ou industrial", "entrada", "interestadual", True),
    ("2919", "Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial", "entrada", "interestadual", True),
    ("2920", "Entrada de vasilhame ou sacaria", "entrada", "interestadual", False),
    ("2921", "Retorno de vasilhame ou sacaria", "entrada", "interestadual", False),
    ("2922", "Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro", "entrada", "interestadual", False),
    ("2923", "Entrada de mercadoria recebida do vendedor remetente, em venda à ordem", "entrada", "interestadual", False),
    ("2924", "Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente", "entrada", "interestadual", False),
    ("2925", "Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente", "entrada", "interestadual", False),
    ("2932", "Aquisição de serviços de transporte iniciado em estado diverso", "entrada", "interestadual", False),
    ("2933", "Aquisição de serviço tributado pelo ISSQN", "entrada", "interestadual", False),
    ("2949", "Outra entrada de mercadoria ou prestação de serviço não especificada", "entrada", "interestadual", False),

    # ── Entradas do exterior (3xxx) ─────────────────────────────────────────
    ("3101", "Compra para industrialização ou produção rural", "entrada", "exterior", False),
    ("3102", "Compra para comercialização", "entrada", "exterior", False),
    ("3126", "Compra para utilização na prestação de serviço", "entrada", "exterior", False),
    ("3127", "Compra para industrialização sob o regime de drawback", "entrada", "exterior", False),
    ("3201", "Devolução de venda de produção do estabelecimento", "entrada", "exterior", True),
    ("3202", "Devolução de venda de mercadoria adquirida ou recebida de terceiros", "entrada", "exterior", True),
    ("3205", "Anulação de valor relativo a prestação de serviço de comunicação", "entrada", "exterior", False),
    ("3206", "Anulação de valor relativo a prestação de serviço de transporte", "entrada", "exterior", False),
    ("3207", "Anulação de valor relativo à venda de energia elétrica", "entrada", "exterior", False),
    ("3251", "Compra de energia elétrica para distribuição ou comercialização", "entrada", "exterior", False),
    ("3301", "Aquisição de serviço de comunicação para execução de serviço da mesma natureza", "entrada", "exterior", False),
    ("3351", "Aquisição de serviço de transporte para execução de serviço da mesma natureza", "entrada", "exterior", False),
    ("3352", "Aquisição de serviço de transporte por estabelecimento industrial", "entrada", "exterior", False),
    ("3353", "Aquisição de serviço de transporte por estabelecimento comercial", "entrada", "exterior", False),
    ("3401", "Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária", "entrada", "exterior", False),
    ("3503", "Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação", "entrada", "exterior", True),
    ("3551", "Compra de bem para o ativo imobilizado", "entrada", "exterior", False),
    ("3553", "Devolução de transferência de bem do ativo imobilizado", "entrada", "exterior", True),
    ("3556", "Compra de material para uso ou consumo", "entrada", "exterior", False),
    ("3651", "Compra de combustível ou lubrificante para industrialização subseqüente", "entrada", "exterior", False),
    ("3652", "Compra de combustível ou lubrificante para comercialização", "entrada", "exterior", False),
    ("3653", "Compra de combustível ou lubrificante por consumidor ou usuário final", "entrada", "exterior", False),
    ("3900", "Outras entradas de mercadorias ou aquisições de serviços", "entrada", "exterior", False),
    ("3949", "Outra entrada de mercadoria ou prestação de serviço não especificada", "entrada", "exterior", False),

    # ── Saídas internas (5xxx) ──────────────────────────────────────────────
    ("5101", "Venda de produção do estabelecimento", "saida", "intraestadual", False),
    ("5102", "Venda de mercadoria adquirida ou recebida de terceiros", "saida", "intraestadual", False),
    ("5103", "Venda de produção do estabelecimento, efetuada fora do estabelecimento", "saida", "intraestadual", False),
    ("5104", "Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento", "saida", "intraestadual", False),
    ("5105", "Venda de produção do estabelecimento que não deva por ele transitar", "saida", "intraestadual", False),
    ("5106", "Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar", "saida", "intraestadual", False),
    ("5109", "Venda de sucata de embalagem, de origem nacional, com ICMS cobrado por substituição tributária", "saida", "intraestadual", False),
    ("5110", "Venda de produção do estabelecimento destinada à ZFM ou ALC", "saida", "intraestadual", False),
    ("5111", "Venda de mercadoria adquirida ou recebida de terceiros para comercialização, destinada à ZFM ou ALC", "saida", "intraestadual", False),
    ("5112", "Venda de produção do estabelecimento remetida anteriormente em consignação industrial", "saida", "intraestadual", False),
    ("5113", "Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil", "saida", "intraestadual", False),
    ("5114", "Venda de produção do estabelecimento remetida anteriormente em consignação mercantil", "saida", "intraestadual", False),
    ("5115", "Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil", "saida", "intraestadual", False),
    ("5116", "Venda de produção do estabelecimento originada de encomenda para recebimento futuro", "saida", "intraestadual", False),
    ("5117", "Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para recebimento futuro", "saida", "intraestadual", False),
    ("5118", "Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário", "saida", "intraestadual", False),
    ("5119", "Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário", "saida", "intraestadual", False),
    ("5120", "Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem", "saida", "intraestadual", False),
    ("5122", "Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente", "saida", "intraestadual", False),
    ("5123", "Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente", "saida", "intraestadual", False),
    ("5124", "Industrialização efetuada para outra empresa", "saida", "intraestadual", False),
    ("5125", "Industrialização efetuada para outra empresa quando a mercadoria remetida para esse fim não transitou pelo estabelecimento adquirente da mercadoria", "saida", "intraestadual", False),
    ("5150", "Transferências de produção própria ou de terceiros", "saida", "intraestadual", False),
    ("5151", "Transferência de produção do estabelecimento", "saida", "intraestadual", False),
    ("5152", "Transferência de mercadoria adquirida ou recebida de terceiros", "saida", "intraestadual", False),
    ("5153", "Transferência de energia elétrica", "saida", "intraestadual", False),
    ("5154", "Transferência para utilização na prestação de serviço", "saida", "intraestadual", False),
    ("5155", "Transferência de produção do estabelecimento, que permanece no depositário", "saida", "intraestadual", False),
    ("5156", "Transferência de mercadoria adquirida ou recebida de terceiros, que permanece no depositário", "saida", "intraestadual", False),
    ("5200", "Devoluções de compras para industrialização, produção rural, comercialização", "saida", "intraestadual", True),
    ("5201", "Devolução de compra para industrialização ou produção rural", "saida", "intraestadual", True),
    ("5202", "Devolução de compra para comercialização", "saida", "intraestadual", True),
    ("5205", "Anulação de valor relativo à aquisição de serviço de comunicação", "saida", "intraestadual", False),
    ("5206", "Anulação de valor relativo à aquisição de serviço de transporte", "saida", "intraestadual", False),
    ("5207", "Anulação de valor relativo à compra de energia elétrica", "saida", "intraestadual", False),
    ("5208", "Devolução de produção do estabelecimento, recebida em transferência", "saida", "intraestadual", True),
    ("5209", "Devolução de mercadoria adquirida ou recebida de terceiros, recebida em transferência", "saida", "intraestadual", True),
    ("5210", "Devolução de compras para utilização na prestação de serviço", "saida", "intraestadual", True),
    ("5250", "Vendas de energia elétrica", "saida", "intraestadual", False),
    ("5251", "Venda de energia elétrica para distribuição ou comercialização", "saida", "intraestadual", False),
    ("5252", "Venda de energia elétrica para estabelecimento industrial", "saida", "intraestadual", False),
    ("5253", "Venda de energia elétrica para estabelecimento comercial", "saida", "intraestadual", False),
    ("5254", "Venda de energia elétrica para estabelecimento prestador de serviço de transporte", "saida", "intraestadual", False),
    ("5255", "Venda de energia elétrica para estabelecimento prestador de serviços de comunicação", "saida", "intraestadual", False),
    ("5256", "Venda de energia elétrica para estabelecimento de produtor rural", "saida", "intraestadual", False),
    ("5257", "Venda de energia elétrica para uso ou consumo", "saida", "intraestadual", False),
    ("5300", "Prestações de serviços de comunicação", "saida", "intraestadual", False),
    ("5301", "Prestação de serviço de comunicação para execução de serviço da mesma natureza", "saida", "intraestadual", False),
    ("5302", "Prestação de serviço de comunicação a estabelecimento industrial", "saida", "intraestadual", False),
    ("5303", "Prestação de serviço de comunicação a estabelecimento comercial", "saida", "intraestadual", False),
    ("5304", "Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte", "saida", "intraestadual", False),
    ("5305", "Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica", "saida", "intraestadual", False),
    ("5306", "Prestação de serviço de comunicação a estabelecimento de produtor rural", "saida", "intraestadual", False),
    ("5307", "Prestação de serviço de comunicação a não contribuinte", "saida", "intraestadual", False),
    ("5350", "Prestações de serviços de transporte", "saida", "intraestadual", False),
    ("5351", "Prestação de serviço de transporte para execução de serviço da mesma natureza", "saida", "intraestadual", False),
    ("5352", "Prestação de serviço de transporte a estabelecimento industrial", "saida", "intraestadual", False),
    ("5353", "Prestação de serviço de transporte a estabelecimento comercial", "saida", "intraestadual", False),
    ("5354", "Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação", "saida", "intraestadual", False),
    ("5355", "Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica", "saida", "intraestadual", False),
    ("5356", "Prestação de serviço de transporte a estabelecimento de produtor rural", "saida", "intraestadual", False),
    ("5357", "Prestação de serviço de transporte a não contribuinte", "saida", "intraestadual", False),
    ("5359", "Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal", "saida", "intraestadual", False),
    ("5360", "Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte", "saida", "intraestadual", False),
    ("5400", "Saídas de mercadorias sujeitas ao regime de substituição tributária", "saida", "intraestadual", False),
    ("5401", "Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto", "saida", "intraestadual", False),
    ("5402", "Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto", "saida", "intraestadual", False),
    ("5403", "Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto", "saida", "intraestadual", False),
    ("5405", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituído", "saida", "intraestadual", False),
    ("5408", "Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária", "saida", "intraestadual", False),
    ("5409", "Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária", "saida", "intraestadual", False),
    ("5410", "Devolução de compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária", "saida", "intraestadual", True),
    ("5411", "Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária", "saida", "intraestadual", True),
    ("5412", "Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária", "saida", "intraestadual", True),
    ("5413", "Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária", "saida", "intraestadual", True),
    ("5414", "Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária", "saida", "intraestadual", False),
    ("5415", "Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária", "saida", "intraestadual", False),
    ("5450", "Sistemas de integração e parceria rural", "saida", "intraestadual", False),
    ("5451", "Remessa de animal para o campo", "saida", "intraestadual", False),
    ("5452", "Remessa de insumo para produção rural", "saida", "intraestadual", False),
    ("5500", "Remessas com fim específico de exportação e eventuais devoluções", "saida", "intraestadual", False),
    ("5501", "Remessa de produção do estabelecimento, com fim específico de exportação", "saida", "intraestadual", False),
    ("5502", "Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação", "saida", "intraestadual", False),
    ("5503", "Devolução de mercadoria recebida com fim específico de exportação", "saida", "intraestadual", True),
    ("5504", "Remessa de mercadorias para formação de lote de exportação", "saida", "intraestadual", False),
    ("5550", "Operações com bens de ativo imobilizado e materiais de uso e consumo", "saida", "intraestadual", False),
    ("5551", "Venda de bem do ativo imobilizado", "saida", "intraestadual", False),
    ("5552", "Transferência de bem do ativo imobilizado", "saida", "intraestadual", False),
    ("5553", "Devolução de compra de bem para o ativo imobilizado", "saida", "intraestadual", True),
    ("5554", "Remessa de bem do ativo imobilizado para uso fora do estabelecimento", "saida", "intraestadual", False),
    ("5555", "Remessa de bem do ativo imobilizado para uso no estabelecimento de terceiro", "saida", "intraestadual", False),
    ("5556", "Devolução de compra de material de uso ou consumo", "saida", "intraestadual", True),
    ("5557", "Transferência de material de uso ou consumo", "saida", "intraestadual", False),
    ("5600", "Créditos e ressarcimentos de ICMS", "saida", "intraestadual", False),
    ("5601", "Transferência de crédito de ICMS acumulado", "saida", "intraestadual", False),
    ("5602", "Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS", "saida", "intraestadual", False),
    ("5603", "Ressarcimento de ICMS retido por substituição tributária", "saida", "intraestadual", False),
    ("5605", "Transferência de saldo devedor de ICMS de outro estabelecimento da mesma empresa", "saida", "intraestadual", False),
    ("5650", "Saídas de combustíveis, lubrificantes, aditivos e agentes de limpeza", "saida", "intraestadual", False),
    ("5651", "Venda de combustível ou lubrificante de produção do estabelecimento destinados à industrialização subseqüente", "saida", "intraestadual", False),
    ("5652", "Venda de combustível ou lubrificante de produção do estabelecimento destinados à comercialização", "saida", "intraestadual", False),
    ("5653", "Venda de combustível ou lubrificante de produção do estabelecimento destinados a consumidor ou usuário final", "saida", "intraestadual", False),
    ("5654", "Venda de combustível ou lubrificante adquiridos ou recebidos de terceiros destinados à industrialização subseqüente", "saida", "intraestadual", False),
    ("5655", "Venda de combustível ou lubrificante adquiridos ou recebidos de terceiros destinados à comercialização", "saida", "intraestadual", False),
    ("5656", "Venda de combustível ou lubrificante adquiridos ou recebidos de terceiros destinados a consumidor ou usuário final", "saida", "intraestadual", False),
    ("5657", "Remessa de combustível ou lubrificante adquiridos ou recebidos de terceiros para venda fora do estabelecimento", "saida", "intraestadual", False),
    ("5658", "Transferência de combustível ou lubrificante de produção do estabelecimento", "saida", "intraestadual", False),
    ("5659", "Transferência de combustível ou lubrificante adquiridos ou recebidos de terceiros", "saida", "intraestadual", False),
    ("5660", "Devolução de compra de combustível ou lubrificante adquiridos para industrialização subseqüente", "saida", "intraestadual", True),
    ("5661", "Devolução de compra de combustível ou lubrificante adquiridos para comercialização", "saida", "intraestadual", True),
    ("5662", "Devolução de compra de combustível ou lubrificante adquiridos por consumidor ou usuário final", "saida", "intraestadual", True),
    ("5900", "Outras saídas de mercadorias ou prestações de serviços", "saida", "intraestadual", False),
    ("5901", "Remessa para industrialização por encomenda", "saida", "intraestadual", False),
    ("5902", "Retorno de mercadoria utilizada na industrialização por encomenda", "saida", "intraestadual", False),
    ("5903", "Retorno de mercadoria recebida para industrialização e não aplicada no referido processo", "saida", "intraestadual", False),
    ("5904", "Remessa para venda fora do estabelecimento", "saida", "intraestadual", False),
    ("5905", "Remessa para depósito fechado ou armazém geral", "saida", "intraestadual", False),
    ("5906", "Retorno de mercadoria depositada em depósito fechado ou armazém geral", "saida", "intraestadual", False),
    ("5907", "Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral", "saida", "intraestadual", False),
    ("5908", "Remessa de bem por conta de contrato de comodato", "saida", "intraestadual", False),
    ("5909", "Retorno de bem remetido por conta de contrato de comodato", "saida", "intraestadual", False),
    ("5910", "Remessa em bonificação, doação ou brinde", "saida", "intraestadual", False),
    ("5911", "Remessa de amostra grátis", "saida", "intraestadual", False),
    ("5912", "Remessa de mercadoria ou bem para demonstração", "saida", "intraestadual", False),
    ("5913", "Retorno de mercadoria ou bem recebido para demonstração", "saida", "intraestadual", False),
    ("5914", "Remessa de mercadoria ou bem para exposição ou feira", "saida", "intraestadual", False),
    ("5915", "Remessa de mercadoria ou bem para conserto ou reparo", "saida", "intraestadual", False),
    ("5916", "Retorno de mercadoria ou bem recebido para conserto ou reparo", "saida", "intraestadual", False),
    ("5917", "Remessa de mercadoria em consignação mercantil ou industrial", "saida", "intraestadual", False),
    ("5918", "Devolução de mercadoria recebida em consignação mercantil ou industrial", "saida", "intraestadual", True),
    ("5919", "Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial", "saida", "intraestadual", True),
    ("5920", "Remessa de vasilhame ou sacaria", "saida", "intraestadual", False),
    ("5921", "Devolução de vasilhame ou sacaria", "saida", "intraestadual", True),
    ("5922", "Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura", "saida", "intraestadual", False),
    ("5923", "Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado", "saida", "intraestadual", False),
    ("5924", "Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente", "saida", "intraestadual", False),
    ("5925", "Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente", "saida", "intraestadual", False),
    ("5926", "Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação", "saida", "intraestadual", False),
    ("5927", "Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração", "saida", "intraestadual", False),
    ("5928", "Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa", "saida", "intraestadual", False),
    ("5929", "Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também acobertada por documento fiscal emitido por sistema de emissão de cupom fiscal", "saida", "intraestadual", False),
    ("5931", "Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na UF onde iniciado o serviço", "saida", "intraestadual", False),
    ("5932", "Prestação de serviço tributado pelo ISSQN", "saida", "intraestadual", False),
    ("5933", "Prestação de serviço tributado pelo ISSQN", "saida", "intraestadual", False),
    ("5934", "Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado", "saida", "intraestadual", False),
    ("5949", "Outra saída de mercadoria ou prestação de serviço não especificada", "saida", "intraestadual", False),

    # ── Saídas interestaduais (6xxx) ─────────────────────────────────────────
    ("6101", "Venda de produção do estabelecimento", "saida", "interestadual", False),
    ("6102", "Venda de mercadoria adquirida ou recebida de terceiros", "saida", "interestadual", False),
    ("6103", "Venda de produção do estabelecimento, efetuada fora do estabelecimento", "saida", "interestadual", False),
    ("6104", "Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento", "saida", "interestadual", False),
    ("6105", "Venda de produção do estabelecimento que não deva por ele transitar", "saida", "interestadual", False),
    ("6106", "Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar", "saida", "interestadual", False),
    ("6107", "Venda de produção do estabelecimento, destinada a não contribuinte", "saida", "interestadual", False),
    ("6108", "Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte", "saida", "interestadual", False),
    ("6110", "Venda de produção do estabelecimento destinada à ZFM ou ALC", "saida", "interestadual", False),
    ("6111", "Venda de mercadoria adquirida ou recebida de terceiros para comercialização, destinada à ZFM ou ALC", "saida", "interestadual", False),
    ("6112", "Venda de produção do estabelecimento remetida anteriormente em consignação industrial", "saida", "interestadual", False),
    ("6113", "Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil", "saida", "interestadual", False),
    ("6114", "Venda de produção do estabelecimento remetida anteriormente em consignação mercantil", "saida", "interestadual", False),
    ("6115", "Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil", "saida", "interestadual", False),
    ("6116", "Venda de produção do estabelecimento originada de encomenda para recebimento futuro", "saida", "interestadual", False),
    ("6117", "Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para recebimento futuro", "saida", "interestadual", False),
    ("6118", "Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário", "saida", "interestadual", False),
    ("6119", "Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário", "saida", "interestadual", False),
    ("6120", "Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem", "saida", "interestadual", False),
    ("6122", "Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente", "saida", "interestadual", False),
    ("6123", "Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente", "saida", "interestadual", False),
    ("6124", "Industrialização efetuada para outra empresa", "saida", "interestadual", False),
    ("6125", "Industrialização efetuada para outra empresa quando a mercadoria remetida para esse fim não transitou pelo estabelecimento adquirente", "saida", "interestadual", False),
    ("6150", "Transferências de produção própria ou de terceiros", "saida", "interestadual", False),
    ("6151", "Transferência de produção do estabelecimento", "saida", "interestadual", False),
    ("6152", "Transferência de mercadoria adquirida ou recebida de terceiros", "saida", "interestadual", False),
    ("6153", "Transferência de energia elétrica", "saida", "interestadual", False),
    ("6154", "Transferência para utilização na prestação de serviço", "saida", "interestadual", False),
    ("6201", "Devolução de compra para industrialização ou produção rural", "saida", "interestadual", True),
    ("6202", "Devolução de compra para comercialização", "saida", "interestadual", True),
    ("6205", "Anulação de valor relativo à aquisição de serviço de comunicação", "saida", "interestadual", False),
    ("6206", "Anulação de valor relativo à aquisição de serviço de transporte", "saida", "interestadual", False),
    ("6207", "Anulação de valor relativo à compra de energia elétrica", "saida", "interestadual", False),
    ("6208", "Devolução de produção do estabelecimento, recebida em transferência", "saida", "interestadual", True),
    ("6209", "Devolução de mercadoria adquirida ou recebida de terceiros, recebida em transferência", "saida", "interestadual", True),
    ("6210", "Devolução de compras para utilização na prestação de serviço", "saida", "interestadual", True),
    ("6251", "Venda de energia elétrica para distribuição ou comercialização", "saida", "interestadual", False),
    ("6252", "Venda de energia elétrica para estabelecimento industrial", "saida", "interestadual", False),
    ("6253", "Venda de energia elétrica para estabelecimento comercial", "saida", "interestadual", False),
    ("6301", "Prestação de serviço de comunicação para execução de serviço da mesma natureza", "saida", "interestadual", False),
    ("6351", "Prestação de serviço de transporte para execução de serviço da mesma natureza", "saida", "interestadual", False),
    ("6352", "Prestação de serviço de transporte a estabelecimento industrial", "saida", "interestadual", False),
    ("6353", "Prestação de serviço de transporte a estabelecimento comercial", "saida", "interestadual", False),
    ("6354", "Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação", "saida", "interestadual", False),
    ("6356", "Prestação de serviço de transporte a estabelecimento de produtor rural", "saida", "interestadual", False),
    ("6357", "Prestação de serviço de transporte a não contribuinte", "saida", "interestadual", False),
    ("6401", "Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto", "saida", "interestadual", False),
    ("6402", "Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto", "saida", "interestadual", False),
    ("6403", "Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto", "saida", "interestadual", False),
    ("6404", "Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente", "saida", "interestadual", False),
    ("6408", "Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária", "saida", "interestadual", False),
    ("6409", "Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária", "saida", "interestadual", False),
    ("6410", "Devolução de compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária", "saida", "interestadual", True),
    ("6411", "Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária", "saida", "interestadual", True),
    ("6412", "Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária", "saida", "interestadual", True),
    ("6413", "Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária", "saida", "interestadual", True),
    ("6500", "Remessas com fim específico de exportação e eventuais devoluções", "saida", "interestadual", False),
    ("6501", "Remessa de produção do estabelecimento, com fim específico de exportação", "saida", "interestadual", False),
    ("6502", "Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação", "saida", "interestadual", False),
    ("6503", "Devolução de mercadoria recebida com fim específico de exportação", "saida", "interestadual", True),
    ("6504", "Remessa de mercadorias para formação de lote de exportação", "saida", "interestadual", False),
    ("6551", "Venda de bem do ativo imobilizado", "saida", "interestadual", False),
    ("6552", "Transferência de bem do ativo imobilizado", "saida", "interestadual", False),
    ("6553", "Devolução de compra de bem para o ativo imobilizado", "saida", "interestadual", True),
    ("6554", "Remessa de bem do ativo imobilizado para uso fora do estabelecimento", "saida", "interestadual", False),
    ("6555", "Remessa de bem do ativo imobilizado para uso no estabelecimento de terceiro", "saida", "interestadual", False),
    ("6556", "Devolução de compra de material de uso ou consumo", "saida", "interestadual", True),
    ("6557", "Transferência de material de uso ou consumo", "saida", "interestadual", False),
    ("6603", "Ressarcimento de ICMS retido por substituição tributária", "saida", "interestadual", False),
    ("6651", "Venda de combustível ou lubrificante de produção do estabelecimento destinados à industrialização subseqüente", "saida", "interestadual", False),
    ("6652", "Venda de combustível ou lubrificante de produção do estabelecimento destinados à comercialização", "saida", "interestadual", False),
    ("6653", "Venda de combustível ou lubrificante de produção do estabelecimento destinados a consumidor ou usuário final", "saida", "interestadual", False),
    ("6654", "Venda de combustível ou lubrificante adquiridos ou recebidos de terceiros destinados à industrialização subseqüente", "saida", "interestadual", False),
    ("6655", "Venda de combustível ou lubrificante adquiridos ou recebidos de terceiros destinados à comercialização", "saida", "interestadual", False),
    ("6656", "Venda de combustível ou lubrificante adquiridos ou recebidos de terceiros destinados a consumidor ou usuário final", "saida", "interestadual", False),
    ("6657", "Remessa de combustível ou lubrificante adquiridos ou recebidos de terceiros para venda fora do estabelecimento", "saida", "interestadual", False),
    ("6658", "Transferência de combustível ou lubrificante de produção do estabelecimento", "saida", "interestadual", False),
    ("6659", "Transferência de combustível ou lubrificante adquiridos ou recebidos de terceiros", "saida", "interestadual", False),
    ("6660", "Devolução de compra de combustível ou lubrificante adquiridos para industrialização subseqüente", "saida", "interestadual", True),
    ("6661", "Devolução de compra de combustível ou lubrificante adquiridos para comercialização", "saida", "interestadual", True),
    ("6662", "Devolução de compra de combustível ou lubrificante adquiridos por consumidor ou usuário final", "saida", "interestadual", True),
    ("6900", "Outras saídas de mercadorias ou prestações de serviços", "saida", "interestadual", False),
    ("6901", "Remessa para industrialização por encomenda", "saida", "interestadual", False),
    ("6902", "Retorno de mercadoria utilizada na industrialização por encomenda", "saida", "interestadual", False),
    ("6903", "Retorno de mercadoria recebida para industrialização e não aplicada no referido processo", "saida", "interestadual", False),
    ("6904", "Remessa para venda fora do estabelecimento", "saida", "interestadual", False),
    ("6905", "Remessa para depósito fechado ou armazém geral", "saida", "interestadual", False),
    ("6906", "Retorno de mercadoria depositada em depósito fechado ou armazém geral", "saida", "interestadual", False),
    ("6907", "Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral", "saida", "interestadual", False),
    ("6908", "Remessa de bem por conta de contrato de comodato", "saida", "interestadual", False),
    ("6909", "Retorno de bem remetido por conta de contrato de comodato", "saida", "interestadual", False),
    ("6910", "Remessa em bonificação, doação ou brinde", "saida", "interestadual", False),
    ("6911", "Remessa de amostra grátis", "saida", "interestadual", False),
    ("6912", "Remessa de mercadoria ou bem para demonstração", "saida", "interestadual", False),
    ("6913", "Retorno de mercadoria ou bem recebido para demonstração", "saida", "interestadual", False),
    ("6914", "Remessa de mercadoria ou bem para exposição ou feira", "saida", "interestadual", False),
    ("6915", "Remessa de mercadoria ou bem para conserto ou reparo", "saida", "interestadual", False),
    ("6916", "Retorno de mercadoria ou bem recebido para conserto ou reparo", "saida", "interestadual", False),
    ("6917", "Remessa de mercadoria em consignação mercantil ou industrial", "saida", "interestadual", False),
    ("6918", "Devolução de mercadoria recebida em consignação mercantil ou industrial", "saida", "interestadual", True),
    ("6920", "Remessa de vasilhame ou sacaria", "saida", "interestadual", False),
    ("6921", "Devolução de vasilhame ou sacaria", "saida", "interestadual", True),
    ("6922", "Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura", "saida", "interestadual", False),
    ("6923", "Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado", "saida", "interestadual", False),
    ("6924", "Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente", "saida", "interestadual", False),
    ("6925", "Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente", "saida", "interestadual", False),
    ("6929", "Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também acobertada por documento fiscal emitido por sistema de emissão de cupom fiscal", "saida", "interestadual", False),
    ("6932", "Prestação de serviço tributado pelo ISSQN", "saida", "interestadual", False),
    ("6949", "Outra saída de mercadoria ou prestação de serviço não especificada", "saida", "interestadual", False),

    # ── Exportações (7xxx) ──────────────────────────────────────────────────
    ("7101", "Venda de produção do estabelecimento", "saida", "exterior", False),
    ("7102", "Venda de mercadoria adquirida ou recebida de terceiros", "saida", "exterior", False),
    ("7105", "Venda de produção do estabelecimento, que não deva por ele transitar", "saida", "exterior", False),
    ("7106", "Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar", "saida", "exterior", False),
    ("7127", "Venda de produção do estabelecimento sob o regime de drawback", "saida", "exterior", False),
    ("7129", "Venda de insumo importado e de mercadoria industrializada sob o regime de drawback", "saida", "exterior", False),
    ("7201", "Devolução de compra para industrialização ou produção rural", "saida", "exterior", True),
    ("7202", "Devolução de compra para comercialização", "saida", "exterior", True),
    ("7205", "Anulação de valor relativo à aquisição de serviço de comunicação", "saida", "exterior", False),
    ("7206", "Anulação de valor relativo à aquisição de serviço de transporte", "saida", "exterior", False),
    ("7207", "Anulação de valor relativo à compra de energia elétrica", "saida", "exterior", False),
    ("7210", "Devolução de compras para utilização na prestação de serviço", "saida", "exterior", True),
    ("7211", "Devolução de compras para industrialização sob o regime de drawback", "saida", "exterior", True),
    ("7251", "Venda de energia elétrica para o exterior", "saida", "exterior", False),
    ("7301", "Prestação de serviço de comunicação para execução de serviço da mesma natureza", "saida", "exterior", False),
    ("7358", "Prestação de serviço de transporte", "saida", "exterior", False),
    ("7501", "Exportação de mercadorias recebidas com fim específico de exportação", "saida", "exterior", False),
    ("7504", "Exportação de mercadorias recebidas com fim específico de exportação", "saida", "exterior", False),
    ("7551", "Venda de bem do ativo imobilizado", "saida", "exterior", False),
    ("7553", "Devolução de compra de bem para o ativo imobilizado", "saida", "exterior", True),
    ("7556", "Devolução de compra de material de uso ou consumo", "saida", "exterior", True),
    ("7651", "Venda de combustível ou lubrificante de produção do estabelecimento", "saida", "exterior", False),
    ("7654", "Venda de combustível ou lubrificante adquiridos ou recebidos de terceiros", "saida", "exterior", False),
    ("7667", "Venda de combustível ou lubrificante a consumidor ou usuário final", "saida", "exterior", False),
    ("7900", "Outras saídas de mercadorias ou prestações de serviços", "saida", "exterior", False),
    ("7930", "Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime aduaneiro especial", "saida", "exterior", True),
    ("7949", "Outra saída de mercadoria ou prestação de serviço não especificada", "saida", "exterior", False),
]
# fmt: on


def upgrade() -> None:
    op.create_table(
        "cfop_reference",
        sa.Column("cfop", sa.String(4), primary_key=True),
        sa.Column("descricao", sa.String(255), nullable=False),
        sa.Column("tipo_operacao", sa.String(20), nullable=False),
        sa.Column("escopo", sa.String(20), nullable=False),
        sa.Column("permite_devolucao", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("ativo", sa.Boolean(), nullable=False, server_default="true"),
    )
    op.create_index("ix_cfop_tipo_operacao", "cfop_reference", ["tipo_operacao"])
    op.create_index("ix_cfop_escopo", "cfop_reference", ["escopo"])

    op.bulk_insert(
        sa.table(
            "cfop_reference",
            sa.column("cfop", sa.String),
            sa.column("descricao", sa.String),
            sa.column("tipo_operacao", sa.String),
            sa.column("escopo", sa.String),
            sa.column("permite_devolucao", sa.Boolean),
            sa.column("ativo", sa.Boolean),
        ),
        [
            {
                "cfop": c[0],
                "descricao": c[1],
                "tipo_operacao": c[2],
                "escopo": c[3],
                "permite_devolucao": c[4],
                "ativo": True,
            }
            for c in _CFOPS
        ],
    )


def downgrade() -> None:
    op.drop_index("ix_cfop_escopo", table_name="cfop_reference")
    op.drop_index("ix_cfop_tipo_operacao", table_name="cfop_reference")
    op.drop_table("cfop_reference")
